### ISSUE TITLE
Add electron-react-boilerplate

### ISSUE THREAD

**Issue by SIholin** [duck-duck-tag/duck-duck-tag#27]
https://github.com/electron-react-boilerplate/electron-react-boilerplate
Estimate: 4h

Time spent: ?

Reviewed: Juho
Triviaalisti nähdään, että EBR on pistetty mukaan.

**Comment by kriskrok** [comment]
Needs to be pruned from disproportinate amounts of surplus configurations, e.g. there still remains amidst others, substitute production configs for transpiling SASS in production builds.
